### ISSUE TITLE
how to query null dimension?

### ISSUE THREAD

**Issue by admanheart** [zapr-oss/druidry#100]
hi:
  i want to query druid like this sql: select * from table_a where name is null. i use EXPLAIN PLAN FOR in dsql, and it show me filter with : {"type":"selector","dimension":"name","value":null,"extractionFn":null}, but i find error when use: SelectorFilter("name", null) , and SelectorFilter("name") with private access error.how should i query this?

**Comment by abhi-zapr** [comment]
Hi, 
Yes currently with overloaded constructors you can't use `SelectorFilter("name", null)` and also can't use `SelectorFilter("name")` as it's private. Need to apply patch for this bug.

**Comment by admanheart** [comment]
ok, got it.

**Comment by abhi-zapr** [comment]
This is fixed in v.30
Now you can query null like this : 
`SelectorFilter filter = new SelectorFilter("Hello", Optional.ofNullable(null));`
