### ISSUE TITLE
Does druidry support nested groupBy Queries?

### ISSUE THREAD

**Issue by pds3095** [zapr-oss/druidry#109]
https://druid.apache.org/docs/latest/querying/datasource.html

Query Data source type can be used for the nested group by. Does Druid support that?

**Comment by abhi-zapr** [comment]
Currently Druidry doesn't support all data source types. 
But there is a patch #87 open and we are planning to release it in 3.0 release as it's a breaking change.

For now if you want you can pull that patch and build druidry locally to achieve your use case.

**Comment by abhi-zapr** [comment]
release this support in v3.0
