### ISSUE TITLE
Classes are not testable, missing Equals and Hashcode method

### ISSUE THREAD

**Issue by paruljain21** [zapr-oss/druidry#14]
Currently, Druidry classes like DruidFilter, DruidDimensions, Granularity all are not testable. It makes it difficult to test the code created using these classes. Please add Equals and hashcode method to make them testable.

**Comment by hgvanpariya** [comment]
@GG-Zapr , I've updated DruidFilter, please provide your comments ...

**Comment by hgvanpariya** [comment]
@GG-Zapr , do you want to add it manually ?

**Comment by GG-Zapr** [comment]
Hi @hgvanpariya, code reviewed and added comment

**Comment by hgvanpariya** [comment]
@GG-Zapr : update the code, please provide your comments ...

**Comment by GG-Zapr** [comment]
Hi @paruljain21,

We have overridden methods in v2.4.
It will be available via Maven Central in a few hours.

@hgvanpariya, Thanks for your first contribution. Together, we can build more into this project helping developers working with Druid.
