### ISSUE TITLE
No Implemetation of DimensionSpec class

### ISSUE THREAD

**Issue by abhisranjan** [zapr-oss/druidry#143]
A not abstract class which extends DimensionSpec is required to use this feature. Currently the client has to create a new class to make an object

**Comment by abhi-zapr** [comment]
Hey @abhisranjan 
I believe you are referring to https://druid.apache.org/docs/latest/querying/dimensionspecs.html druid doc for dimension spec.
Implementation of most (if not all) are already available in library.
You can checkout under package `in.zapr.druid.druidry.dimension` and `in.zapr.druid.druidry.extractionFunctions`.

Does this resolve your issue ?
