### ISSUE TITLE
granularity setting

### ISSUE THREAD

**Issue by SJYeon** [zapr-oss/druidry#32]
How should I set the timezone of granularity  to Asia/Hong_Kong? And where can I find the API file? Thanks!

**Comment by GG-Zapr** [comment]
I am assuming you are talking about Period Granularity.
Please find sample code:

`
private final static String PERIOD = "PT1H";
private final static String TIMEZONE = "Asia/Hong_Kong";
`
`
DateTime originDate = new DateTime(DateTimeZone.forID(TIMEZONE));
PeriodGranularity granularity = PeriodGranularity.builder()
                .origin(originDate)
                .period(PERIOD)
                .timeZone(DateTimeZone.forID(TIMEZONE))
                .build();`

Let me know if you face any issues or I have missed anything.

**Comment by GG-Zapr** [comment]
We use Joda library for DateTime.
API doc for the same: http://joda-time.sourceforge.net/timezones.html

**Comment by SJYeon** [comment]
Thank you very much !!
