### ISSUE TITLE
IntervalFilter  里面的类型没有初始化值，是否应该初始化值为interval

### ISSUE THREAD

**Issue by xbtq77** [zapr-oss/druidry#35]
public class IntervalFilter extends DruidFilter {

    private static String INTERVAL_DRUID_FILTER_TYPE = "interval";

    private String type;
    private String dimension;
    private List<Interval> intervals;

    public IntervalFilter(String dimension, List<Interval> intervals) {
        this.dimension = dimension;
        this.intervals = intervals;
    }

    // TODO: support for Extraction Function
}

**Comment by GG-Zapr** [comment]
I am assuming the bug here is type is not being set, which is causing an invalid query.

We will provide a fix by tomorrow EOD.
If there is any more bug, let us know.

**Comment by GG-Zapr** [comment]
Hi @xbtq77, we have fixed the issue and released v2.3.
It should be available within few hours.
