### ISSUE TITLE
any support for pagingspec

### ISSUE THREAD

**Issue by WanliTian** [zapr-oss/druidry#39]
any support for pagingspec?

**Comment by GG-Zapr** [comment]
Hi @WanliTian, 

Awaiting your reply.

**Comment by mihirp90** [comment]
Is select query now supporting pagingspec?

**Comment by abhi-zapr** [comment]
Yes @mihirp90 & @WanliTian druid select query provides support for `pagingSpec` and now in druidry's `DruidSelectQuery` there's option to use `pagingspec`.  Hope this resolves your issue.
