### ISSUE TITLE
Enum type resolution problem?

### ISSUE THREAD

**Issue by davyWong3** [zapr-oss/druidry#41]
The (ObjectMapper's) writeValueAsString method handles Enum type properly, as seen in the console. However ,when it goes to the query method defined in DruidJerseyClient , the Entity.entity method seems to resolve the Enum type（QueryType） inproperly . From the server log, it seems that the query couldn't be parsed. My druidry version is 2.3.

`@Override
    public <T> List<T> query(DruidQuery druidQuery, Class<T> className) throws QueryException {
        try (Response response = this.queryWebTarget
                .request(MediaType.APPLICATION_JSON)
                .post(Entity.entity(druidQuery, MediaType.APPLICATION_JSON))) {
   ...
`

The server log shows "Exception occurred on request [unparsable query]
com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'TIMESERIES' into a subtype of [simple type, class io.druid.query.Query]"

Thanks for any comments.

**Comment by nihit-zapr** [comment]
Hi,

Thanks for using Druidry.

We tested the code and we couldnt replicate your issue. We are able to
parse TIMESERIES enum. However if you are using some other version of
Jackson explicitly, there might be some issue. Can you provide details
about which Jackson version are you using. We are currently using 2.8.6
version of Jackson in Druidry. If you are explicitly using older version
try to upgrade and check.

Thanks
Nihit

**Comment by davyWong3** [comment]
Hi, 
Thanks for your reply. I'm not using other version of Jackson explicitly. 
However, I find that the fastjson i'm using may have some conflicts  with druidry. When i exclude fastjson （which has an optional dependency of javax.ws.rs 2.0.1） , the query method defined in DruidJerseyClient behaves normally.  I haven't figure out the exact cause yet.

**Comment by nihit-zapr** [comment]
Hi,

Jackson version needs to be compatible with Jersey client. You can check
what minimum version of jackson is required for the current jersey client
in druidry in Maven Central.

**Comment by nihit-zapr** [comment]
@davyWong3 We are closing this issue. If you have any other issues we are ready to help.
Thanks
