### ISSUE TITLE
Builder for DruidSearchQuery

### ISSUE THREAD

**Issue by HomoEfficio** [zapr-oss/druidry#44]
There are builders in aggregation query like `DruidGroupByQuery`, `DruidTopNQuery`, but there is no builder in `DruidSearchQuery`.

**Comment by nihit-zapr** [comment]
Hey @HomoEfficio,
Ya there seems to be a bug. Is it possible for you to raise a pr for this? We will merge as soon as possible.

**Comment by HomoEfficio** [comment]
OK. I will try.

**Comment by GG-Zapr** [comment]
Hi @HomoEfficio,

We have added builder and released v2.4.

It will be in available via Maven Central in some hours.
Thanks for contributing to our project.
