### ISSUE TITLE
skipEmptyBuckets Context Not Support

### ISSUE THREAD

**Issue by zhaomoran** [zapr-oss/druidry#45]
I found timeseries  query  can set 
```
"context" : {
    "skipEmptyBuckets": "true"
 }
```
 to support Zero-filling 。

But I can not found it in druidry

**Comment by nihit-zapr** [comment]
Hi @zhaomoran,
This is specific to timeseries. We need to think on how to implement this. As of now we have same `context` for all query types. We might need to change implementation for each query type to support this or we may need to create specific Jackon Serializer. 

We might take some time to think about this. Please feel to help us if its really urgent. 

Thanks

**Comment by nihit-zapr** [comment]
@zhaomoran Meanwhile you can extend class and implement if its urgent.

**Comment by zhaomoran** [comment]
@nihit-zapr I have done this already.But I found that `context` constructor is protected, I guess that was caused by Lombok. I think I have to modify and compile from your source code. This is not a big problem.

Thanks

**Comment by burningice2012** [comment]
I implemented this feature by myself too, by re-write the Context class.
I would suggest that remove dependency of Lombok from 
in.zapr.druid.druidry.Context.java, as it's not quite convenient to extend right now

**Comment by abhi-zapr** [comment]
Added this support in release v3.0
