### ISSUE TITLE
411 Length Required

### ISSUE THREAD

**Issue by swiftSnail** [zapr-oss/druidry#46]
after query druid got http status code 411. after set the property blow to `ClientConfig` get resloved.

                this.jerseyConfig.property(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.BUFFERED);

**Comment by GG-Zapr** [comment]
Hi @swiftSnail,

We followed the 3 approaches

`ClientConfig clientConfig = new ClientConfig();
clientConfig.property(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.BUFFERED);
DruidClient client = new DruidJerseyClient(druidConfiguration, clientConfig);`

`ClientConfig clientConfig = new ClientConfig();
clientConfig.property(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.CHUNKED);
DruidClient client = new DruidJerseyClient(druidConfiguration, clientConfig);`

`
DruidClient client = new DruidJerseyClient(druidConfiguration, clientConfig);`

We were not able to reproduce the issue. 
Please provide with more details (whatever is possible) such as 

- Druid Version 
- If there is another version of Jersey related dependency
- Code snippet where it is throwing 411

Any other details would be helpful.

**Comment by GG-Zapr** [comment]
Hi @swiftSnail,

Please provide more details. It will help us in solving the issue.

**Comment by swiftSnail** [comment]
hi @GG-Zapr 
we are using druid-0.10.1 and should have no more jersey dependency.
our code is 
```
private static DruidConfiguration configuration = DruidConfiguration.builder()
            .protocol(DruidQueryProtocol.HTTP)
            .port(80)
            .host("domain.through.nginx")
            .endpoint("druid/v2")
            .build();
    private static final DruidClient DRUID_CLIENT = new DruidJerseyClient(configuration);
    
    DRUID_CLIENT.connect();

    DRUID_CLIENT.query(query, className);
```
will it be better if expose org.glassfish.jersey.client.ClientConfig？

**Comment by GG-Zapr** [comment]
It is probably the issue with nginx. It would help if you can tell us the nginx version.

Links:

1. https://groups.google.com/forum/#!msg/dropwizard-user/cHRaOA3_6M8/GTlJV2QL6LwJ
2. https://serverfault.com/questions/164220/is-there-a-way-to-avoid-nginx-411-content-length-required-errors

**Comment by swiftSnail** [comment]
we are using nginx/1.2.9.

can you make ClientConfig settable?

**Comment by GG-Zapr** [comment]
DruidClient constructor allows you to set custom ClientConfig. (refer: https://github.com/zapr-oss/druidry/issues/46#issuecomment-422435237)

Would that not suffice in your case.

Let me know if you still it settable with a usecase.
