### ISSUE TITLE
Support for histogram extension

### ISSUE THREAD

**Issue by GG-Zapr** [zapr-oss/druidry#61]
Already partial support is already merged in a separate branch `extension-histogram`

**Comment by patilvikram** [comment]
@GG-Zapr I think this is already being implemented?

**Comment by GG-Zapr** [comment]
Partial implementation was present.
Complete implementation is under review.
PR for the same: https://github.com/zapr-oss/druidry/pull/85

**Comment by GG-Zapr** [comment]
Released in v2.13
