### ISSUE TITLE
Distinct Count

### ISSUE THREAD

**Issue by gsratti** [zapr-oss/druidry#65]
Is distinct count aggregator supported in druid dry? If not, is there any way to include disticnt count in aggregates?
http://druid.io/docs/latest/development/extensions-contrib/distinctcount.html

**Comment by abhi-zapr** [comment]
hey @gsratti 
Currently druidry doesn't support **distinct count aggregator**. 
Regarding adding support for the same, if you have already written it you can raise the PR or we will add support for it by the end of the week.
Thanks.

**Comment by abhi-zapr** [comment]
Hi @gsratti 
Added support for Distinct Count in v2.10 release.
Closing this issue.
Thanks.
