### ISSUE TITLE
Request for supporting HAVING clause

### ISSUE THREAD

**Issue by huanzhang** [zapr-oss/druidry#71]
I need to filter groupBy query results which is like the HAVING clause in SQL.
Druid doc: http://druid.io/docs/latest/querying/having.html

**Comment by moezubair** [comment]
I can pick this up if no one else is looking into it

**Comment by GG-Zapr** [comment]
@moezubair That would be great. Thanks

**Comment by iamshreeram** [comment]
Hi @moezubair , Do you have any updates on _Having_ clause? Any idea when will you be pushing the changes?

**Comment by anaskhan96** [comment]
Hi @moezubair , same query as @iamshreeram . Any idea when this can be wrapped up?

**Comment by piotrm50** [comment]
I implemented this feature in PR #113

**Comment by abhi-zapr** [comment]
Added support with v3.0
