### ISSUE TITLE
TimeFormatExtractionFunction can't extraction day of week number

### ISSUE THREAD

**Issue by stepanovD** [zapr-oss/druidry#80]
TimeFormatExtractionFunction use SimpleDateFormat as format. But the petterns used in this class are different from Joda DateTimeFormat. DateTimeFormat has 'e' pattern for day of week number when SimpleDateFormat use pattern 'u'. SimpleDateFormat not supported pettern 'e'.

**Comment by GG-Zapr** [comment]
We will fix it in the next release

**Comment by GG-Zapr** [comment]
Fixed in release v2.12
