### ISSUE TITLE
Druid Authentication

### ISSUE THREAD

**Issue by pbalaguer19** [zapr-oss/druidry#98]
Hi!
I have added an authentication step in my Druid environment. How can I continue using this library?

**Comment by abhi-zapr** [comment]
Hey @pbalaguer19 
Currently Druidry doesn't support authentication. For this, need to implement authentication feature in DruidJerseyClient.
Reference : [jersey-authentication]( https://jersey.github.io/documentation/latest/client.html#d0e5461)

Currently we are working on other issues. If you can create a patch and raise a pull request that would be great.
